name: BigB-website Actions CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
         html_file: 'index.html'
       
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Code checkout
        uses: actions/checkout@v3

      - name: Run tests
        working-directory: ${{env.SRC_DIR}}
        run: go test -coverprofile=covprofile ./...

      - name: Check scripts with Shellcheck
        uses: essentialkaos/htmlcov-action@v1
        with:
          path: ${{env.SRC_DIR}}
          profile: covprofile
