name: BigB-website Actions CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
         html_file: 'index.html'
         
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
         root: 'index.html'
         blacklist: invalid
