name: BigB-website Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
         html_file: 'index.html'
